name: "Dependecies Test [Cron]"

on:
  schedule:
    - cron: "0 16 * * 5"

jobs:
  cron-test:
    name: Dependecies Test [Cron]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          # this is regarding the matrix strategy specified above
          node-version: ${{ matrix.node-version }}

      - name: Check Dependencies
        run: npm ci
