name: Heroku Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Heroku Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_app_name: 'quarantine-gaming'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          procfile: 'web: node ./src/main.js'
          buildpack: 'https://github.com/heroku/heroku-buildpack-nodejs.git'
          healthcheck: 'https://quarantine-gaming.herokuapp.com'
          rollbackonhealthcheckfailed: true
          checkstring: 'online'
          delay: 30
